name: beneficiary_management_system
description: Offline-first beneficiary management app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # HTTP
  dio: ^5.4.0
  intl: ^0.19.0

  # Offline storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.0

  # Connectivity
  connectivity_plus: ^6.0.2

  # UI packages
  fluttertoast: ^8.2.4

  # Dot Env
  flutter_dotenv: ^5.1.0  # Latest version as of now; check pub.dev for updates

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
