name: my_offline_app
description: Offline-first UNICEF-style beneficiary system
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.4.0

  # State management
  provider: ^6.1.2

  # Offline database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # JWT decode
  jwt_decoder: ^2.0.1

  # Connectivity
  connectivity_plus: ^6.0.1

  # UUID for local records
  uuid: ^4.3.3

  # Form helpers
  intl: ^0.19.0

  # Icons
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_lints: ^3.0.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
